import random

SUPPORTED_EXTENSIONS = (".mp4", ".mov", ".mkv", ".avi", ".webm")

MAX_INTRO_SKIP_SECONDS = 20.0
ENERGY_THRESHOLD_RATIO = 0.50
MAX_BEAT_SNAP_DISTANCE = 1.0

BEATS_PER_PHRASE = 16

MIN_SEGMENT_SECONDS = 45.0
MAX_SEGMENT_SECONDS = 110.0
DEFAULT_SEGMENT_SECONDS = 75.0

TIMING_JITTER_SECONDS = 0.025

MIN_CROSSFADE_SECONDS = 6.0
MAX_CROSSFADE_SECONDS = 40.0

LOW_ENERGY = 0.30
HIGH_ENERGY = 0.70

MIN_ONSET_DENSITY_FOR_BEAT = 0.05
MIN_BEAT_COUNT_FOR_LOCK = 4

KEY_DIFFERENCE_WEIGHT = 20.0

TARGET_LUFS = -14
TARGET_TRUE_PEAK = -1.5
TARGET_LRA = 11

FFMPEG_AUDIO_CODEC = "aac"

TRANSITION_TYPES = (
    "crossfade",
    "crossfade",
    "crossfade",
    "fade_black",
)

ENABLE_FADE_BLACK_TRANSITIONS = False

ENABLE_SLIDE_TRANSITIONS = False

SLIDE_SIDES = ("left", "right", "top", "bottom")

ZOOM_PUNCH_MAX_SCALE = 1.15

CROSSFADE_BARS_HIGH_ENERGY = (2.0, 4.0)
CROSSFADE_BARS_MID_ENERGY = (4.0, 6.0)
CROSSFADE_BARS_LOW_ENERGY = (6.0, 8.0)

MIN_DURATION_FOR_SMART_BLEND = 1.5

BASS_CUTOFF_HZ = 250.0

BASS_SWAP_OUTGOING_END_FRACTION = 0.45
BASS_SWAP_INCOMING_START_FRACTION = 0.10
BASS_SWAP_INCOMING_FULL_FRACTION = 0.55

MAX_TEMPO_STRETCH = 0.08

VOCAL_BAND_LOW_HZ = 300.0
VOCAL_BAND_HIGH_HZ = 3400.0

VOCAL_ACTIVITY_SEARCH_PHRASES = 2

VOCAL_START_WEIGHT = 5.0

ARC_BPM_WEIGHT = 0.35

ARC_BPM_PERCENTILE_LOW = 20
ARC_BPM_PERCENTILE_HIGH = 80

SIREN_PROBABILITY = 0.20
SCRATCH_PROBABILITY = 0.15
AIR_HORN_PROBABILITY = 0.10
RISER_PROBABILITY = 0.15
IMPACT_PROBABILITY = 0.10

DJ_EFFECT_MIX_GAIN = 0.35

DJ_EFFECT_MAX_SECONDS = 2.5

DJ_EFFECT_FADE_IN_SECONDS = 0.15
DJ_EFFECT_FADE_OUT_SECONDS = 0.8

SIREN_FREQ_LOW_HZ = 500.0
SIREN_FREQ_HIGH_HZ = 1400.0
SIREN_SWEEP_RATE_HZ = 2.0

AIR_HORN_CHORD_HZ = (233.0, 293.0, 349.0)

SCRATCH_RATE_HZ = 3.0
SCRATCH_WINDOW_SECONDS = 0.6

RISER_BAND_LOW_HZ = 800.0
RISER_BAND_HIGH_HZ = 6000.0

IMPACT_START_FREQ_HZ = 900.0
IMPACT_END_FREQ_HZ = 55.0

DEFAULT_VISUALIZER_BARS = 24
VISUALIZER_BACKGROUND_TOP_COLOR = (20, 20, 32)
VISUALIZER_BACKGROUND_BOTTOM_COLOR = (8, 8, 14)
VISUALIZER_BAR_COLOR_LOW = (70, 130, 255)
VISUALIZER_BAR_COLOR_HIGH = (255, 70, 150)
VISUALIZER_BAR_CORNER_RADIUS_RATIO = 0.5
VISUALIZER_REFLECTION_HEIGHT_RATIO = 0.18
VISUALIZER_REFLECTION_OPACITY = 0.35
VISUALIZER_FFT_HOP_LENGTH = 1024
VISUALIZER_BAR_FMIN_HZ = 40.0

VISUALIZER_BAR_ATTACK_SECONDS = 0.05
VISUALIZER_BAR_DECAY_SECONDS = 0.35

VISUALIZER_BEAT_PULSE_DECAY_SECONDS = 0.12
VISUALIZER_BEAT_PULSE_BRIGHTEN = 40
VISUALIZER_BEAT_PULSE_ATTACK_SECONDS = 0.08

VISUALIZER_BACKGROUND_HUE_DRIFT = 0.08

SPEAKER_ENABLED = True
SPEAKER_POSITION_X_RATIO_LEFT = 0.15
SPEAKER_POSITION_X_RATIO_RIGHT = 0.85
SPEAKER_POSITION_Y_RATIO = 0.20
SPEAKER_BASE_RADIUS_RATIO = 0.05
SPEAKER_MAX_EXTRA_RADIUS_RATIO = 0.035
SPEAKER_RIM_WIDTH_RATIO = 0.012
SPEAKER_RIM_COLOR = (35, 35, 45)
SPEAKER_ATTACK_SECONDS = 0.03
SPEAKER_DECAY_SECONDS = 0.15

TITLE_FONT_SIZE_RATIO = 0.06
TITLE_PILL_COLOR = (10, 10, 18)
TITLE_PILL_OPACITY = 150
TITLE_ACCENT_COLOR = (255, 70, 150)
TITLES_JSON_FILENAME = "titles.json"

TRACKLIST_DURATION_SECONDS = 6.0

TRACKLIST_CROSSFADE_SECONDS = 1.5

random.seed()